<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengakses_model extends CI_Model
{

    public $table = 'master_pengakses';
    public $id = 'id_pengakses';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->load->helper('my_datatable');
        $this->datatables->select('id_pengakses,nm_pengakses,kode_bank');
        $this->datatables->from('master_pengakses');
        //add this line for join
        //$this->datatables->join('table2', 'master_pengakses.field = table2.field');
        $this->datatables->edit_column('id_pengakses', '$1', 'encrypt_id(id_pengakses)');
        $this->datatables->add_column('action', anchor(site_url('pengakses/update/$1'), 'Update') . " | " . anchor(site_url('pengakses/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_pengakses');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_pengakses', $q);
        $this->db->or_like('nm_pengakses', $q);
        $this->db->or_like('kode_bank', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pengakses', $q);
        $this->db->or_like('nm_pengakses', $q);
        $this->db->or_like('kode_bank', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return true;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pengakses_model.php */
/* Location: ./application/models/Pengakses_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-05-15 10:20:28 */
/* http://harviacode.com */
